version: '3.8'
services:
    pepe-aptos:
        restart: always
        image: pepe-aptos:${TAG}
        env_file:
          - .env.production
        networks:
          - production
networks:
  production:
    name: production
    external: true
